# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/asus/X00TD/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter X00TD X00TD_4_4,$(TARGET_DEVICE)),)

endif
